export const ADD_USER = 'ADD_USER';
export const GET_USER_LIST = 'GET_USER_LIST';

export const GET_CURRENT_USER = 'GETU_SER'; 
export const TOGGLE_CURRENT_USER = 'TOGGLE_USER';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';
export const LOAD_ARTICLES_FROM_LOCALSTORE = 'LOAD_ARTICLES_FROM_LOCALSTORE';

export const IS_LOADER = 'IS_LOADER';
export const IS_NOT_LOADER = 'IS_NOT_LOADER';